### Reset all stored values in db
POST {{baseUrl}}/admin/reset

### Create a new user
POST {{baseUrl}}/api/users

{
  "email": "{{emailExample1}}",
  "password": "{{passwordExample1}}"
}

### Login as user to get jwt
# @name login
POST {{baseUrl}}/api/login

{
  "email": "{{emailExample1}}",
  "password": "{{passwordExample1}}"
}

### Try to post a new chirp using the bad token
POST {{baseUrl}}/api/chirps
Authorization: Bearer {{login.response.body.refreshToken}}

{
  "body": "Let’s just say I know a guy... who knows a guy... who knows another guy."
}

### Post a new chirp with the correct token
POST {{baseUrl}}/api/chirps
Authorization: Bearer {{login.response.body.token}}

{
  "body": "Let’s just say I know a guy... who knows a guy... who knows another guy."
}